import { useSettingsStore } from '../../../store/settingsStore';

const EN = {
  // header
  'greet.morning': 'Good morning',
  'greet.afternoon': 'Good afternoon',
  'greet.evening': 'Good evening',
  'header.streamFor': 'This stream: {t}',
  'header.twitch': 'Twitch',
  'header.obs': 'OBS',
  'header.on': 'connected',
  'header.off': 'not connected',
  'header.profile': 'Layout',
  'header.customize': 'Customize',
  'header.done': 'Done',
  'profile.ranked': 'Ranked Grind',
  'profile.chatting': 'Just Chatting',
  'profile.speedrun': 'Speedrun / Challenge',
  // edit mode
  'edit.hint': 'Drag cards to reorder, pick a width, or remove what you do not need.',
  'edit.add': 'Add widget',
  'edit.reset': 'Reset layout',
  'edit.allAdded': 'Every widget is on your dashboard.',
  'edit.remove': 'Remove widget',
  'edit.moveEarlier': 'Move earlier',
  'edit.moveLater': 'Move later',
  'edit.width': 'Width',
  'size.4': 'S',
  'size.6': 'M',
  'size.8': 'L',
  'size.12': 'Full',
  // widget names + descriptions
  'w.pulse': 'Stream Pulse',
  'w.pulse.desc': 'Live numbers for this stream: time, messages, chatters, follows, raids, gifts.',
  'w.activity': 'Chat Activity',
  'w.activity.desc': 'Messages per minute over the last half hour.',
  'w.feed': 'Live Feed',
  'w.feed.desc': 'Follows, raids, gifts, redemptions and duels as they happen.',
  'w.leaderboard': 'Leaderboards',
  'w.leaderboard.desc': 'Top chatters, duelists, gifters and reward redeemers.',
  'w.counter': 'Counter',
  'w.counter.desc': 'Your counters with quick +1, -1 and reset.',
  'w.title': 'Stream Title',
  'w.title.desc': 'See and change the live Twitch title.',
  'w.keybinds': 'Global Keybinds',
  'w.keybinds.desc': 'Master switch and quick toggles for your hotkeys.',
  'w.reply': 'Auto-Reply',
  'w.reply.desc': 'Toggle a chat reply or AI rule on the fly.',
  'w.overlay': 'Chat Overlay',
  'w.overlay.desc': 'Copy the OBS browser source URL or open the designer.',
  'w.quickrun': 'Quick Run',
  'w.quickrun.desc': 'Fire any sequence with one click.',
  'w.checklist': 'Stream Checklist',
  'w.checklist.desc': 'A pre-stream checklist you can tick off and reset.',
  // pulse
  'pulse.time': 'On air',
  'pulse.messages': 'Messages',
  'pulse.chatters': 'Chatters',
  'pulse.follows': 'Follows',
  'pulse.raids': 'Raid viewers',
  'pulse.gifts': 'Subs gifted',
  'pulse.redemptions': 'Redemptions',
  'pulse.duels': 'Duels',
  'pulse.perMin': '{n}/min',
  'pulse.newStream': 'Start new stream',
  'pulse.newStreamHint': 'Resets "this stream" numbers and the stream leaderboard. All-time totals stay.',
  'pulse.tiles': 'Tiles',
  'pulse.shown': 'Shown (drag or use the arrows to reorder)',
  'pulse.hidden': 'Hidden (click to add)',
  'pulse.removeTile': 'Hide tile',
  // activity
  'activity.now': 'now',
  'activity.peak': 'Peak {n}/min',
  'activity.avg': 'Last 5 min',
  'activity.empty': 'Waiting for chat. Messages will draw the curve.',
  'activity.minutesAgo': '{n} min ago',
  // feed
  'feed.empty': 'Nothing yet. Follows, raids, gifts and redemptions show up here live.',
  'feed.follow': 'followed',
  'feed.raid': 'raided with {n} viewers',
  'feed.gift': 'gifted {n} sub(s)',
  'feed.redeem': 'redeemed {x}',
  'feed.duel': 'beat {x} in a duel',
  'feed.streak': 'is on a {n}-stream watch streak',
  // leaderboard
  'lb.messages': 'Chat',
  'lb.duelWins': 'Duels',
  'lb.gifts': 'Gifts',
  'lb.redemptions': 'Rewards',
  'lb.unit.messages': 'msgs',
  'lb.unit.duelWins': 'wins',
  'lb.unit.gifts': 'subs',
  'lb.unit.redemptions': 'redeems',
  'lb.title.messages': 'Top chatters',
  'lb.title.duelWins': 'Top duelists',
  'lb.title.gifts': 'Top gifters',
  'lb.title.redemptions': 'Top redeemers',
  'lb.stream': 'This stream',
  'lb.allTime': 'All time',
  'lb.empty': 'No one on the board yet. It fills as your chat gets going.',
  'lb.post': 'Post to chat',
  'lb.posted': 'Posted',
  'lb.postFailed': 'Could not post',
  'lb.includeStreamer': 'Include me',
  'lb.reset': 'Reset all stats',
  'lb.resetConfirm': 'Clear every leaderboard, the feed and the chart? This cannot be undone.',
  'lb.record': '{w}W · {l}L',
  'lb.points': '{n} pts',
  // counter
  'counter.none': 'No counters yet.',
  'counter.add': 'Add Counter',
  'counter.decrement': 'Decrement (-1)',
  'counter.increment': 'Increment (+1)',
  'counter.reset': 'Reset counter',
  'counter.syncing': 'Syncing to {f}',
  'counter.obsOff': 'OBS output off',
  'counter.titleSync': 'Auto Stream Title Sync',
  'counter.live': 'LIVE',
  'counter.toggleSync': 'Toggle counter stream title sync',
  // title
  'title.current': 'Live Twitch title',
  'title.refresh': 'Refresh',
  'title.empty': 'No title set or offline',
  'title.placeholder': 'Enter new stream title…',
  'title.update': 'Update',
  'title.updated': 'Stream title updated!',
  // keybinds
  'keybinds.label': 'Hotkeys',
  'keybinds.allOn': 'All enabled',
  'keybinds.paused': 'Paused',
  'keybinds.none': 'No global keybinds registered.',
  'keybinds.add': 'Add in Settings',
  'keybinds.master': 'Master keybinds switch',
  // reply
  'reply.command': 'Chat command',
  'reply.ai': 'AI reply',
  'reply.prepared': 'Prepared',
  'reply.active': 'Active',
  'reply.disabled': 'Disabled',
  'reply.aiDefault': 'Responds intelligently to chatter messages',
  'reply.cooldown': 'Cooldown: {n}s',
  'reply.rank': 'Rank: {r}',
  'reply.everyone': 'everyone',
  'reply.none': 'No auto-replies yet.',
  'reply.create': 'Create in Commands',
  'reply.toggle': 'Toggle auto reply rule',
  // overlay
  'overlay.stage': 'OBS Browser Source',
  'overlay.blurb': 'Chat renders in OBS with zero cloud delay. Paste the URL into a Browser Source at 1920 × 1080.',
  'overlay.copy': 'Copy OBS URL',
  'overlay.copied': 'Copied',
  'overlay.open': 'Open Designer',
  // quick run
  'run.none': 'No sequences yet. Build one in Commands.',
  'run.go': 'Run',
  'run.running': 'Running…',
  'run.filter': 'Filter sequences…',
  'run.create': 'Open Commands',
  'run.disabled': 'Disabled',
  'run.noMatch': 'No sequence matches.',
  // checklist
  'check.placeholder': 'Add a step…',
  'check.add': 'Add',
  'check.reset': 'Uncheck all',
  'check.progress': '{a} of {b} done',
  'check.allDone': 'All set. Go live!',
  'check.remove': 'Remove',
  'check.empty': 'Nothing on the list.',
};

export type HomeTextKey = keyof typeof EN;

const AR: Record<HomeTextKey, string> = {
  'greet.morning': 'صباح الخير',
  'greet.afternoon': 'مساء الخير',
  'greet.evening': 'مساء الخير',
  'header.streamFor': 'مدة البث: {t}',
  'header.twitch': 'تويتش',
  'header.obs': 'OBS',
  'header.on': 'متصل',
  'header.off': 'غير متصل',
  'header.profile': 'التخطيط',
  'header.customize': 'تخصيص',
  'header.done': 'تم',
  'profile.ranked': 'تحدي الرانكد',
  'profile.chatting': 'دردشة فقط',
  'profile.speedrun': 'سبيدران / تحدي',
  'edit.hint': 'اسحب البطاقات لإعادة الترتيب، اختر العرض، أو احذف ما لا تحتاجه.',
  'edit.add': 'إضافة عنصر',
  'edit.reset': 'استعادة التخطيط',
  'edit.allAdded': 'كل العناصر موجودة في لوحتك.',
  'edit.remove': 'حذف العنصر',
  'edit.moveEarlier': 'تقديم',
  'edit.moveLater': 'تأخير',
  'edit.width': 'العرض',
  'size.4': 'ص',
  'size.6': 'م',
  'size.8': 'ك',
  'size.12': 'كامل',
  'w.pulse': 'البث',
  'w.pulse.desc': 'أرقام مباشرة لهذا البث: الوقت والرسائل والمتابعون والريدات والهدايا.',
  'w.activity': 'نشاط الشات',
  'w.activity.desc': 'عدد الرسائل في الدقيقة خلال آخر نصف ساعة.',
  'w.feed': 'الأحداث المباشرة',
  'w.feed.desc': 'المتابعات والريدات والهدايا والمكافآت والتحديات لحظة حدوثها.',
  'w.leaderboard': 'لوحات المتصدرين',
  'w.leaderboard.desc': 'أكثر المتحدثين والمتحدّين والمُهدين والمستبدلين للمكافآت.',
  'w.counter': 'العدّاد',
  'w.counter.desc': 'عدّاداتك مع +1 و -1 وإعادة التعيين السريعة.',
  'w.title': 'عنوان البث',
  'w.title.desc': 'اعرض وغيّر عنوان تويتش المباشر.',
  'w.keybinds': 'اختصارات عامة',
  'w.keybinds.desc': 'مفتاح رئيسي وتبديلات سريعة لاختصاراتك.',
  'w.reply': 'الرد التلقائي',
  'w.reply.desc': 'فعّل أو عطّل رداً أو قاعدة ذكاء اصطناعي بسرعة.',
  'w.overlay': 'أوفرلاي الشات',
  'w.overlay.desc': 'انسخ رابط OBS أو افتح المصمم.',
  'w.quickrun': 'تشغيل سريع',
  'w.quickrun.desc': 'شغّل أي سلسلة بضغطة واحدة.',
  'w.checklist': 'قائمة قبل البث',
  'w.checklist.desc': 'قائمة تحضير تضع عليها علامة وتعيد ضبطها.',
  'pulse.time': 'على الهواء',
  'pulse.messages': 'الرسائل',
  'pulse.chatters': 'المتحدثون',
  'pulse.follows': 'المتابعات',
  'pulse.raids': 'مشاهدو الريد',
  'pulse.gifts': 'اشتراكات مُهداة',
  'pulse.redemptions': 'المكافآت',
  'pulse.duels': 'التحديات',
  'pulse.perMin': '{n}/د',
  'pulse.newStream': 'بدء بث جديد',
  'pulse.newStreamHint': 'يصفّر أرقام «هذا البث» ولوحة المتصدرين الحالية. الإجماليات الكلية تبقى.',
  'pulse.tiles': 'البطاقات',
  'pulse.shown': 'الظاهرة (اسحب أو استخدم الأسهم لإعادة الترتيب)',
  'pulse.hidden': 'المخفية (اضغط للإضافة)',
  'pulse.removeTile': 'إخفاء البطاقة',
  'activity.now': 'الآن',
  'activity.peak': 'الذروة {n}/د',
  'activity.avg': 'آخر 5 دقائق',
  'activity.empty': 'بانتظار الشات. الرسائل سترسم المنحنى.',
  'activity.minutesAgo': 'قبل {n} د',
  'feed.empty': 'لا شيء بعد. المتابعات والريدات والهدايا والمكافآت تظهر هنا مباشرة.',
  'feed.follow': 'تابع',
  'feed.raid': 'ريد بـ {n} مشاهد',
  'feed.gift': 'أهدى {n} اشتراك',
  'feed.redeem': 'استبدل {x}',
  'feed.duel': 'هزم {x} في تحدٍّ',
  'feed.streak': 'لديه سلسلة مشاهدة {n}',
  'lb.messages': 'الشات',
  'lb.duelWins': 'التحديات',
  'lb.gifts': 'الهدايا',
  'lb.redemptions': 'المكافآت',
  'lb.unit.messages': 'رسالة',
  'lb.unit.duelWins': 'فوز',
  'lb.unit.gifts': 'اشتراك',
  'lb.unit.redemptions': 'استبدال',
  'lb.title.messages': 'أكثر المتحدثين',
  'lb.title.duelWins': 'أفضل المتحدّين',
  'lb.title.gifts': 'أكثر المُهدين',
  'lb.title.redemptions': 'أكثر المستبدلين',
  'lb.stream': 'هذا البث',
  'lb.allTime': 'كل الأوقات',
  'lb.empty': 'لا أحد في اللوحة بعد. تمتلئ مع نشاط الشات.',
  'lb.post': 'نشر في الشات',
  'lb.posted': 'تم النشر',
  'lb.postFailed': 'تعذّر النشر',
  'lb.includeStreamer': 'أضفني',
  'lb.reset': 'تصفير كل الإحصاءات',
  'lb.resetConfirm': 'مسح كل لوحات المتصدرين والأحداث والمنحنى؟ لا يمكن التراجع.',
  'lb.record': '{w} فوز · {l} خسارة',
  'lb.points': '{n} نقطة',
  'counter.none': 'لا توجد عدّادات بعد.',
  'counter.add': 'إضافة عدّاد',
  'counter.decrement': 'إنقاص (-1)',
  'counter.increment': 'زيادة (+1)',
  'counter.reset': 'إعادة تعيين العدّاد',
  'counter.syncing': 'مزامنة مع {f}',
  'counter.obsOff': 'إخراج OBS متوقف',
  'counter.titleSync': 'مزامنة عنوان البث تلقائياً',
  'counter.live': 'مباشر',
  'counter.toggleSync': 'تبديل مزامنة عنوان البث مع العدّاد',
  'title.current': 'عنوان تويتش الحالي',
  'title.refresh': 'تحديث',
  'title.empty': 'لا عنوان أو غير متصل',
  'title.placeholder': 'اكتب عنوان البث الجديد…',
  'title.update': 'تحديث',
  'title.updated': 'تم تحديث عنوان البث!',
  'keybinds.label': 'الاختصارات',
  'keybinds.allOn': 'الكل مفعّل',
  'keybinds.paused': 'متوقفة',
  'keybinds.none': 'لا توجد اختصارات عامة.',
  'keybinds.add': 'أضف من الإعدادات',
  'keybinds.master': 'المفتاح الرئيسي للاختصارات',
  'reply.command': 'أمر شات',
  'reply.ai': 'رد ذكي',
  'reply.prepared': 'جاهز',
  'reply.active': 'مفعّل',
  'reply.disabled': 'معطّل',
  'reply.aiDefault': 'يرد بذكاء على رسائل المتحدثين',
  'reply.cooldown': 'الانتظار: {n} ث',
  'reply.rank': 'الرتبة: {r}',
  'reply.everyone': 'الجميع',
  'reply.none': 'لا توجد ردود تلقائية بعد.',
  'reply.create': 'أنشئ من الأوامر',
  'reply.toggle': 'تبديل قاعدة الرد التلقائي',
  'overlay.stage': 'مصدر متصفح OBS',
  'overlay.blurb': 'يُعرض الشات في OBS دون تأخير سحابي. الصق الرابط في Browser Source بدقة 1920 × 1080.',
  'overlay.copy': 'نسخ رابط OBS',
  'overlay.copied': 'تم النسخ',
  'overlay.open': 'فتح المصمم',
  'run.none': 'لا توجد سلاسل بعد. أنشئ واحدة من الأوامر.',
  'run.go': 'تشغيل',
  'run.running': 'قيد التشغيل…',
  'run.filter': 'ابحث في السلاسل…',
  'run.create': 'فتح الأوامر',
  'run.disabled': 'معطّلة',
  'run.noMatch': 'لا توجد سلسلة مطابقة.',
  'check.placeholder': 'أضف خطوة…',
  'check.add': 'إضافة',
  'check.reset': 'إلغاء تحديد الكل',
  'check.progress': 'تم {a} من {b}',
  'check.allDone': 'كل شيء جاهز. ابدأ البث!',
  'check.remove': 'حذف',
  'check.empty': 'القائمة فارغة.',
};

export type HomeText = (key: HomeTextKey, vars?: Record<string, string | number>) => string;

export function translateHome(lang: 'en' | 'ar', key: HomeTextKey, vars?: Record<string, string | number>): string {
  const template = (lang === 'ar' ? AR : EN)[key] ?? EN[key];
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_, name: string) => String(vars[name] ?? ''));
}

export function useHomeText(): { h: HomeText; lang: 'en' | 'ar' } {
  const language = useSettingsStore((s) => s.language);
  const lang = language === 'ar' ? 'ar' : 'en';
  return { h: (key, vars) => translateHome(lang, key, vars), lang };
}
